name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            devopswithsam/argodemo:latest
            devopswithsam/argodemo:${{ github.run_number }}
      - name: Clone Repository B
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'iam-sameera'
          repository: 'argocd-k8s-deploy'

      - name: Access cloned repository content
        run: |
          cd argocd-k8s-deploy
          sed -i "s/devopswithsam\/argodemo:[0-9]*\|devopswithsam\/argodemo:latest/devopswithsam\/argodemo:${{ github.run_number }}/" deployment.yml
          git config --global user.email "devopssameera@gmail.com"
          git config --global user.name "Sameera Dissanayaka"
          git add deployment.yml
          git commit -m "Update deployment.yml ${{ github.run_number }}"

      - name: Push to Repository argocd-k8s-deploy
        run: |
          cd argocd-k8s-deploy
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/iam-sameera/argocd-k8s-deploy.git
          git push origin main
          
